# Generated by Django 2.2.1 on 2019-05-02 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss', models.IntegerField(max_length=3, verbose_name='丢包率')),
            ],
        ),
        migrations.CreateModel(
            name='Shaping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controling_ip', models.GenericIPAddressField(verbose_name='控制设备ip')),
                ('controlled_ip', models.GenericIPAddressField(verbose_name='被控制设备ip')),
                ('local_port', models.IntegerField(max_length=5, null=True, verbose_name='本地端口')),
                ('remote_port', models.IntegerField(max_length=5, null=True, verbose_name='对端端口')),
                ('profile_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Profile', verbose_name='控制规则id')),
            ],
        ),
    ]
