# Generated by Django 2.2.1 on 2019-05-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shaping',
            old_name='controling_ip',
            new_name='controlling_ip',
        ),
    ]
