# Generated by Django 2.2.1 on 2019-05-02 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190502_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shaping',
            name='profile_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Profile', verbose_name='控制规则id'),
        ),
    ]
