# Generated by Django 2.2.1 on 2019-05-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190502_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='loss',
        ),
        migrations.AddField(
            model_name='profile',
            name='content',
            field=models.TextField(max_length=2048, null=True, verbose_name='规则json字符串'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=16, null=True, verbose_name='规则名称'),
        ),
    ]
