# Generated by Django 2.2.1 on 2019-05-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190503_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='controlled_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='被控制设备ip'),
        ),
        migrations.AddField(
            model_name='profile',
            name='controlling_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='控制设备ip'),
        ),
        migrations.AddField(
            model_name='profile',
            name='iptables',
            field=models.TextField(max_length=2048, null=True, verbose_name='iptables字符串'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mark',
            field=models.IntegerField(null=True, verbose_name='mark标记值'),
        ),
        migrations.DeleteModel(
            name='Shaping',
        ),
    ]
