# Generated by Django 2.2.1 on 2019-05-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20190503_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='tc',
            field=models.TextField(max_length=2048, null=True, verbose_name='tc命令字符串'),
        ),
    ]
