# Generated by Django 2.2.1 on 2019-05-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_info_tc'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='parent_id',
            field=models.IntegerField(null=True, verbose_name='tc parentid'),
        ),
    ]
